

/*
 * Filename: swc_clock.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_clock.h"
#include "clock_type.h"



/* USER CODE START SWC_CLOCK_INCLUDE */

/* USER CODE END SWC_CLOCK_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CLOCK_USERDEFINITIONS */
void clbk_1s();
void clbk_250ms();


/* USER CODE END SWC_CLOCK_USERDEFINITIONS */



/*
* component: swc_Clock
* cycletime: 50
* description: Runnable
* events: 
* name: CLOCK_input_run
* shortname: input
* signalIN: so_button
* signalOUT: so_event
* task: tsk_io
*/
void CLOCK_input_run(RTE_event ev){
	
	/* USER CODE START CLOCK_input_run */
    
    SC_BUTTON_data_t myButton = SC_BUTTON_INIT_DATA;
    SC_EVENT_data_t myEvent   = SC_EVENT_INIT_DATA;
    
    //This runnable is being called every 50 ms, therefore we need a variable that is incremented in 50, 
    //once it reaches 2000, it should set the longpress event. 
    
    static uint16_t timeCounter = 0;
    
    SC_BUTTON_driverIn(&myButton);
    
    if(TRUE == myButton.buttonRightPressed)
    {
        if(2000 > timeCounter) //2000 will be set as the time used for the right press
        {
            timeCounter = timeCounter + 50; //50 because this runnable is called every 50 miliseconds. 
        }
        else if(2000 <= timeCounter)
        {
            myEvent.m_ev = EV_KEYRIGHTLONGPRESS;
            
            RTE_SC_EVENT_set(&SO_EVENT_signal, myEvent);
            
            timeCounter = 0;
        }
        else
        {
            //Intended to do nothing.
        }
    }
    else
    {
        timeCounter = 0;
    }
    
    /* USER CODE END CLOCK_input_run */
}

/*
* component: swc_Clock
* cycletime: 0
* description: Runnable
* events: ev_onUpdate
* name: CLOCK_control_run
* shortname: control
* signalIN: so_event
* signalOUT: so_clock
* task: tsk_control
*/
void CLOCK_control_run(RTE_event ev){
	
	/* USER CODE START CLOCK_control_run */
    
    SC_EVENT_data_t myEvent = RTE_SC_EVENT_get(&SO_EVENT_signal);
    
    STATE_processEvent(&CLOCK_fsm, EVENT(myEvent.m_ev));

    /* USER CODE END CLOCK_control_run */
}

/*
* component: swc_Clock
* cycletime: 250
* description: Runnable
* events: 
* name: CLOCK_display_run
* shortname: display
* signalIN: so_clock
* signalOUT: so_clock_display
* task: tsk_io
*/
void CLOCK_display_run(RTE_event ev){
	
	/* USER CODE START CLOCK_display_run */
    
//    SC_EVENT_data_t myEvent = RTE_SC_EVENT_get(&SO_EVENT_signal);
//    
//    switch(myEvent.m_ev)
//    {
//        case EV_KEYLEFT:
//            UART_LOG_PutString("LEFT BUTTON \n");
//        break;
//            
//        case EV_KEYRIGHT:
//            UART_LOG_PutString("RIGHT BUTTON \n");
//        break;
//            
//        case EV_KEYRIGHTLONGPRESS:
//            UART_LOG_PutString("LONG RIGHT BUTTON \n");
//        break;
//            
//        case EV_250MS:
//            UART_LOG_PutString("250 MS\n");
//        break;
//            
//        case EV_1MIN:
//            UART_LOG_PutString("1 MINUTE \n");
//        break;
//            
//        case EV_NONE:
//            break;
//            
//        default: 
//        break;      
//    }
    
    static boolean_t hourEditing   = FALSE;
    static boolean_t minuteEditing = FALSE;
    
    static uint8_t hourValue   = 0;
    static uint8_t minuteValue = 0;
    
    SC_CLOCK_data_t myClock = RTE_SC_CLOCK_get(&SO_CLOCK_signal);
    
    RTE_SC_CLOCK_set(&SO_CLOCK_DISPLAY_signal, myClock);
    
    if (hourValue != myClock.m_hours.m_currentValue || minuteValue != myClock.m_minutes.m_currentValue || hourEditing != myClock.m_hours.m_fontEditing || minuteEditing != myClock.m_minutes.m_fontEditing) 
    {
        RTE_SC_CLOCK_pushPort(&SO_CLOCK_DISPLAY_signal);
        
        hourValue     = myClock.m_hours.m_currentValue;
        minuteValue   = myClock.m_minutes.m_currentValue;
        
        hourEditing   = myClock.m_hours.m_fontEditing;
        minuteEditing = myClock.m_minutes.m_fontEditing;
    }
    else
    {
        //Intended to do nothing.
    }
        
    /* USER CODE END CLOCK_display_run */
}

/* USER CODE START SWC_CLOCK_FUNCTIONS */

//Calback Function for the 1 Minute alarm
void clbk_1s()
{
    static uint8_t secondCounter = 0;
    
    secondCounter++;
    
    if(60 <= secondCounter)
    {
        SC_EVENT_data_t myEv;
        myEv.m_ev = EV_1MIN;  
        secondCounter = 0;
        RTE_SC_EVENT_set(&SO_EVENT_signal, myEv);
    }
    else
    {
        //Intended to do nothing.
    }
}

//Calback Function for the 250 ms alarm
void clbk_250ms()
{
    SC_EVENT_data_t myEv;
    myEv.m_ev = EV_250MS;
    
    RTE_SC_EVENT_set(&SO_EVENT_signal, myEv);
}

/* USER CODE END SWC_CLOCK_FUNCTIONS */

