
/*
 * Filename: swc_clock.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_CLOCK
#define _H_DEFINE_SWC_CLOCK

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_CLOCK_INCLUDES */

/* USER CODE END SWC_CLOCK_INCLUDES */



/* USER CODE START SWC_CLOCK_USERDEFINITIONS */

/* USER CODE END SWC_CLOCK_USERDEFINITIONS */


/*
* component: swc_Clock
* cycletime: 50
* description: Runnable
* events: 
* name: CLOCK_input_run
* shortname: input
* signalIN: so_button
* signalOUT: so_event
* task: tsk_io
*/
void CLOCK_input_run(RTE_event ev);

/*
* component: swc_Clock
* cycletime: 0
* description: Runnable
* events: ev_onUpdate
* name: CLOCK_control_run
* shortname: control
* signalIN: so_event
* signalOUT: so_clock
* task: tsk_control
*/
void CLOCK_control_run(RTE_event ev);

/*
* component: swc_Clock
* cycletime: 250
* description: Runnable
* events: 
* name: CLOCK_display_run
* shortname: display
* signalIN: so_clock
* signalOUT: so_clock_display
* task: tsk_io
*/
void CLOCK_display_run(RTE_event ev);


#endif