

/*
 * Filename: tsk_io.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_io.h"



/* USER CODE START TSK_IO_INCLUDE */

/* USER CODE END TSK_IO_INCLUDE */

#include "swc_clock.h"



/* USER CODE START TSK_IO_USERDEFINITIONS */

/* USER CODE END TSK_IO_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable_tsk_io[] = {
	{ CLOCK_input_run, 50 },	//Runnable for the input of the clock
	{ CLOCK_display_run, 250 },	//Runnable
};
const uint16_t RTE_cyclicActivation_tsk_io_size = sizeof (RTE_cyclicActivationTable_tsk_io) / sizeof(RTE_cyclicTable_t); 

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_io[] = {
    { CLOCK_input_run, ev_1ms },  //Runnable for the input of the clock
    { CLOCK_input_run, ev_event_onData },  //Runnable for the input of the clock
    { CLOCK_display_run, ev_1ms },  //Runnable
    { CLOCK_display_run, ev_event_onData },  //Runnable
}; 
const uint16_t RTE_eventActivation_tsk_io_size = sizeof (RTE_eventActivationTable_tsk_io) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
* description: This task will contain all IO operations, e.g. remote, engine,...
* events: ev_1ms|ev_event_onData
* mode: Cyclic and Event
* name: tsk_io
* shortname: io
* signalpoolsRO: sp_common
* signalpoolsRW: sp_common
* tickEvent: ev_1ms
* timertickperiod: 1
*/
TASK(tsk_io)
{
	/* ticktime of the task */
	static uint32_t ticktime = 0;
	
    EventMaskType ev = 0;
    
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_1ms|ev_event_onData);
        GetEvent(tsk_io,&ev);
        ClearEvent(ev);
    
		/* USER CODE START TSK_IO_TASKBOBY_PRE */

		/* USER CODE END TSK_IO_TASKBODY_PRE */
        
        if (ev & ev_1ms){
            //Process Cyclic table on tick
            RTE_ProcessCyclicTable(RTE_cyclicActivationTable_tsk_io, RTE_cyclicActivation_tsk_io_size, ticktime);

			ticktime += 1;
			if (ticktime > 0xFFFFFF00) ticktime = 0;

		};
		
		//Process data driven events
		RTE_ProcessEventTable(RTE_eventActivationTable_tsk_io, RTE_eventActivation_tsk_io_size, ev);
		
		/* USER CODE START TSK_IO_TASKBODY_POST */

		/* USER CODE END TSK_IO_TASKBODY_POST */

        
    }
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_IO_ISR */

/* USER CODE END TSK_IO_ISR */

