

/*
 * Filename: sc_button_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_button_type.h"



/* USER CODE START SC_BUTTON_INCLUDE */

/* USER CODE END SC_BUTTON_INCLUDE */


/*
* description: Signalclass for the button
* name: sc_button
* shortname: button
*/

/* USER CODE START SC_BUTTON_USERDEFINITIONS */

/* USER CODE END SC_BUTTON_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_BUTTON signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_BUTTON_driverIn(SC_BUTTON_data_t *const data)
{
	/* USER CODE START driverInSC_BUTTON */
//#error "Add your code here"

	//Read data from the MCAL driver
    data->buttonLeftPressed  = BUTTON_IsPressed(BUTTON_1);
    
    data->buttonRightPressed = BUTTON_IsPressed(BUTTON_2);

	return RC_SUCCESS;
	/* USER CODE END driverInSC_BUTTON */
}



