
/*
 * Filename: sc_clock_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SC_CLOCK_TYPE
#define _H_DEFINE_SC_CLOCK_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"
#include "statemachine.h"

/* USER CODE START SC_CLOCK_INCLUDES */
#include<stdio.h>
#include <stdlib.h>
#include "tft.h"
    
/* USER CODE END SC_CLOCK_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_CLOCK signal    
 **********************************************************************/

/* USER CODE START SC_CLOCK_USERDEFINITIONS */

/* USER CODE END SC_CLOCK_USERDEFINITIONS */
    
typedef enum {
    CLOCK_C_ISEDITINGHOURS,
    CLOCK_C_ISEDITINGMINUTES,
    CLOCK_C_ISDISPLAYING,
    CLOCK_W_ISEDITING,
    CLOCK_W_ISAUTOINCREMENT,
    CLOCK_W_ISDISPLAYING
} CLOCK_state_t;

typedef enum {
    CLOCK_no_widget,
    CLOCK_hour_widget,
    CLOCK_minute_widget
} CLOCK_active_widget_t;

typedef struct
{
//    CLOCK_state_t                   m_state;
//    STATE_stateOuterTransition_t*   m_transitions;
//    uint8_t                         m_value;
//    boolean_t                       m_isEditingFont;
//    STATE_stateAction_t*       m_stateActions;
    uint8_t     m_currentValue;
    uint8_t     m_maxValue;
    uint8_t     m_minValue;
    boolean_t   m_fontEditing;
} CLOCK_widget_t;


	//#error "Provide your data structure"
    //TODO: IMPLEMENT THE STATE MACHINE.
    //USE THE TABLES WHICH WILL USE THE STATE MACHINE STRUCTURES.
    //(TABLES, STATE MACHINE OBJECT DEFINITION AND THE ACTIONS WHICH THE STATE MACHINE WILL DO))
typedef 
/* USER CODE START SC_CLOCK_SIGNALDATADEFINITION */
struct
{    
    CLOCK_active_widget_t   m_activeWidget;
    CLOCK_widget_t          m_hours;
    CLOCK_widget_t          m_minutes;    
} 
/* USER CODE END SC_CLOCK_SIGNALDATADEFINITION */
SC_CLOCK_data_t;

/* USER CODE START InitSC_CLOCK */

//#error "Provide a sensible init value"
#define SC_CLOCK_INIT_DATA ((SC_CLOCK_data_t){CLOCK_no_widget, {0, 23, 1, FALSE},{0, 59, 1, FALSE} })
/* USER CODE END InitSC_CLOCK */


//TODO:
//ENUM WIDGET, ENUM ACTIVE WIDGET, IN THE DATA STRUCT JUST ADD THE 3 MARKED IN THE SLIDE


/**
 * Default OUT driver API
 * \param const SC_CLOCK_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SC_CLOCK_driverOut(const SC_CLOCK_data_t  *const data);


/* USER CODE START SC_CLOCK_USERFUNCTIONS */

/* USER CODE END SC_CLOCK_USERFUNCTIONS */


#endif