

/*
 * Filename: sc_clock_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_clock_type.h"



/* USER CODE START SC_CLOCK_INCLUDE */

/* USER CODE END SC_CLOCK_INCLUDE */


/*
* description: Signalclass for the clock including the hour and the minute widget
* name: sc_clock
* shortname: clock
*/

/* USER CODE START SC_CLOCK_USERDEFINITIONS */

/* USER CODE END SC_CLOCK_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_CLOCK signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_CLOCK_driverOut(const SC_CLOCK_data_t  *const data)
{
	/* USER CODE START driverOutSC_CLOCK */
//#error "Add your code here"

    if(TRUE == data->m_hours.m_fontEditing) 
    {
        TFT_fillRect(8, 55, 45, 35, WHITE);
        TFT_setColors(BLACK, WHITE);
    }
    else 
    {
        TFT_fillRect(8, 55, 45, 35, BLACK);
        TFT_setColors(WHITE, BLACK);
    }
    
    TFT_setCursor(13, 60);
    
    if(data->m_hours.m_currentValue < 10) 
    { 
        TFT_print("0");
    }
    else
    {
        //Intended to do nothing.
    }
    
    char printHours[3];
    itoa(data->m_hours.m_currentValue, printHours, 10);
    
    TFT_print(printHours);
    
    
    TFT_setColors(WHITE, BLACK);
    TFT_setCursor(56, 60);
    TFT_print(":");
    
    
    if(TRUE == data->m_minutes.m_fontEditing) 
    {
        TFT_fillRect(75, 55, 45, 35, WHITE);
        TFT_setColors(BLACK, WHITE);
    }
    else 
    {
        TFT_fillRect(75, 55, 45, 35, BLACK);
        TFT_setColors(WHITE, BLACK);
    }
    
    TFT_setCursor(80, 60);
    
    if(data->m_minutes.m_currentValue < 10) 
    { 
        TFT_print("0");
    }
    else
    {
        //Intended to do nothing.
    }
    
    char printMinutes[3];
    itoa(data->m_minutes.m_currentValue, printMinutes, 10);
    
    TFT_print(printMinutes);

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_CLOCK */
}
