
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */

/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_event.h"
#include "sc_button.h"
#include "sc_clock.h"
#include "sc_clock.h"



/*
* description: A Signal object for the events
* indriver: 0
* name: so_event
* onDataError: 0
* onDataUpdate: ev_onUpdate
* outdriver: 0
* resource: res_My_Resource
* shortname: event
* signalclass: sc_event
* signalpool: sp_common
*/
extern SC_EVENT_t SO_EVENT_signal;


/*
* description: A Signal for the button
* indriver: default
* name: so_button
* onDataError: 0
* onDataUpdate: 0
* outdriver: 0
* resource: None
* shortname: button
* signalclass: sc_button
* signalpool: sp_common
*/
extern SC_BUTTON_t SO_BUTTON_signal;


/*
* description: A Signal for the clock
* indriver: 0
* name: so_clock
* onDataError: 0
* onDataUpdate: 0
* outdriver: 0
* resource: None
* shortname: clock
* signalclass: sc_clock
* signalpool: sp_common
*/
extern SC_CLOCK_t SO_CLOCK_signal;


/*
* description: A Signal
* indriver: 0
* name: so_clock_display
* onDataError: 0
* onDataUpdate: 0
* outdriver: default
* resource: None
* shortname: clock_display
* signalclass: sc_clock
* signalpool: sp_common
*/
extern SC_CLOCK_t SO_CLOCK_DISPLAY_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

#endif