

/*
 * Filename: sc_clock_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_clock_type.h"



/* USER CODE START SC_CLOCK_INCLUDE */

/* USER CODE END SC_CLOCK_INCLUDE */


/*
* description: Signalclass representing the clock widgets
* name: sc_clock
* shortname: clock
*/

/* USER CODE START SC_CLOCK_USERDEFINITIONS */

/* USER CODE END SC_CLOCK_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_CLOCK signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_CLOCK_driverIn(SC_CLOCK_data_t *const data)
{
	/* USER CODE START driverInSC_CLOCK */
#error "Add your code here"

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
	/* USER CODE END driverInSC_CLOCK */
}
/**
 * Default OUT driver API
 */
inline RC_t SC_CLOCK_driverOut(const SC_CLOCK_data_t  *const data)
{
	/* USER CODE START driverOutSC_CLOCK */
#error "Add your code here"

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_CLOCK */
}



