

/*
 * Filename: sc_events_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_events_type.h"



/* USER CODE START SC_EVENTS_INCLUDE */

/* USER CODE END SC_EVENTS_INCLUDE */


/*
* description: Event of clock
* name: sc_events
* shortname: events
*/

/* USER CODE START SC_EVENTS_USERDEFINITIONS */

/* USER CODE END SC_EVENTS_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_EVENTS signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_EVENTS_driverIn(SC_EVENTS_data_t *const data)
{
	/* USER CODE START driverInSC_EVENTS */
#error "Add your code here"

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
	/* USER CODE END driverInSC_EVENTS */
}
/**
 * Default OUT driver API
 */
inline RC_t SC_EVENTS_driverOut(const SC_EVENTS_data_t  *const data)
{
	/* USER CODE START driverOutSC_EVENTS */
#error "Add your code here"

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_EVENTS */
}



