

/*
 * Filename: sc_state_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_state_type.h"



/* USER CODE START SC_STATE_INCLUDE */

/* USER CODE END SC_STATE_INCLUDE */


/*
* description: Signalclass containing the state of the statemachine
* name: sc_state
* shortname: state
*/

/* USER CODE START SC_STATE_USERDEFINITIONS */

/* USER CODE END SC_STATE_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_STATE signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_STATE_driverIn(SC_STATE_data_t *const data)
{
	/* USER CODE START driverInSC_STATE */

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
	/* USER CODE END driverInSC_STATE */
}
/**
 * Default OUT driver API
 */
inline RC_t SC_STATE_driverOut(const SC_STATE_data_t  *const data)
{
	/* USER CODE START driverOutSC_STATE */

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_STATE */
}



