
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */

/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_events.h"
#include "sc_clock.h"



/*
* description: Event
* indriver: default
* name: so_event
* onDataError: 0
* onDataUpdate: ev_event_onData
* outdriver: default
* resource: None
* shortname: event
* signalclass: sc_events
* signalpool: sp_common
*/
extern SC_EVENTS_t SO_EVENT_signal;


/*
* description: A Signal that represents the clock
* indriver: default
* name: so_clock
* onDataError: 0
* onDataUpdate: ev_event_onData
* outdriver: default
* resource: None
* shortname: clock
* signalclass: sc_clock
* signalpool: sp_common
*/
extern SC_CLOCK_t SO_CLOCK_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

#endif