

/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_events.h"
#include "sc_events_type.h"
#include "sc_clock.h"
#include "sc_clock_type.h"



/* signal configuration */
/*
* description: Event
* indriver: default
* name: so_event
* onDataError: 0
* onDataUpdate: ev_event_onData
* outdriver: default
* resource: None
* shortname: event
* signalclass: sc_events
* signalpool: sp_common
*/


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_event_updTasks = { tsk_io, tsk_control };
 

static const SC_EVENTS_cfg_t SO_EVENT_cfg = 
{
   /* indriver           */  SC_EVENTS_driverIn,
   /* outdriver          */  SC_EVENTS_driverOut,

   /* onUpdate           */  ev_event_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  2,
   /* task list onUpdate */  &so_event_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_event */


/* signal data */

SC_EVENTS_t SO_EVENT_signal= 
{
   /* init value    */  SC_EVENTS_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENT_cfg,
}; /* data so_event */

/* signal configuration */
/*
* description: A Signal that represents the clock
* indriver: default
* name: so_clock
* onDataError: 0
* onDataUpdate: ev_event_onData
* outdriver: default
* resource: None
* shortname: clock
* signalclass: sc_clock
* signalpool: sp_common
*/


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_clock_updTasks = { tsk_io, tsk_control };
 

static const SC_CLOCK_cfg_t SO_CLOCK_cfg = 
{
   /* indriver           */  SC_CLOCK_driverIn,
   /* outdriver          */  SC_CLOCK_driverOut,

   /* onUpdate           */  ev_event_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  2,
   /* task list onUpdate */  &so_clock_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_clock */


/* signal data */

SC_CLOCK_t SO_CLOCK_signal= 
{
   /* init value    */  SC_CLOCK_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CLOCK_cfg,
}; /* data so_clock */



void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_EVENTS_incAge( &SO_EVENT_signal, tick); 
   RTE_SC_CLOCK_incAge( &SO_CLOCK_signal, tick); 
   
}


